## Regularization

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
df = pd.read_csv(r"D:\Linear Regression\Modular\Linear-Regression\data\Advertising.csv")
df.head()

TV  radio  newspaper  sales
0  230.1   37.8       69.2   22.1
1   44.5   39.3       45.1   10.4
2   17.2   45.9       69.3    9.3
3  151.5   41.3       58.5   18.5
4  180.8   10.8       58.4   12.9

In [4]:
X = df.drop('sales',axis=1)
X.head()

TV  radio  newspaper
0  230.1   37.8       69.2
1   44.5   39.3       45.1
2   17.2   45.9       69.3
3  151.5   41.3       58.5
4  180.8   10.8       58.4

In [5]:
y = df['sales']
y.head

<bound method NDFrame.head of 0      22.1
1      10.4
2       9.3
3      18.5
4      12.9
       ... 
195     7.6
196     9.7
197    12.8
198    25.5
199    13.4
Name: sales, Length: 200, dtype: float64>

In [8]:
from sklearn.preprocessing import PolynomialFeatures
from sklearn.linear_model import LinearRegression

In [7]:
poly_conv = PolynomialFeatures(degree=3, include_bias=False)

In [10]:
poly_features = poly_conv.fit_transform(X)
poly_features

array([[2.30100000e+02, 3.78000000e+01, 6.92000000e+01, ...,
        9.88757280e+04, 1.81010592e+05, 3.31373888e+05],
       [4.45000000e+01, 3.93000000e+01, 4.51000000e+01, ...,
        6.96564990e+04, 7.99365930e+04, 9.17338510e+04],
       [1.72000000e+01, 4.59000000e+01, 6.93000000e+01, ...,
        1.46001933e+05, 2.20434291e+05, 3.32812557e+05],
       ...,
       [1.77000000e+02, 9.30000000e+00, 6.40000000e+00, ...,
        5.53536000e+02, 3.80928000e+02, 2.62144000e+02],
       [2.83600000e+02, 4.20000000e+01, 6.62000000e+01, ...,
        1.16776800e+05, 1.84062480e+05, 2.90117528e+05],
       [2.32100000e+02, 8.60000000e+00, 8.70000000e+00, ...,
        6.43452000e+02, 6.50934000e+02, 6.58503000e+02]])

In [11]:
X.shape

(200, 3)

In [12]:
poly_features.shape

(200, 19)

In [13]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(
                                    poly_features, y, test_size=0.33, random_state=101)

In [14]:
from sklearn.preprocessing import StandardScaler
scalar = StandardScaler()

In [15]:
scalar.fit(X_train)

StandardScaler()

In [17]:
scaled_X_train = scalar.transform(X_train) 

In [18]:
scaled_X_test = scalar.transform(X_test) 

In [19]:
X_train[0]

array([1.87800000e+02, 2.11000000e+01, 9.50000000e+00, 3.52688400e+04,
       3.96258000e+03, 1.78410000e+03, 4.45210000e+02, 2.00450000e+02,
       9.02500000e+01, 6.62348815e+06, 7.44172524e+05, 3.35053980e+05,
       8.36104380e+04, 3.76445100e+04, 1.69489500e+04, 9.39393100e+03,
       4.22949500e+03, 1.90427500e+03, 8.57375000e+02])

In [20]:
scaled_X_train[0]

array([ 0.455913  , -0.15469995, -0.98899258,  0.23144458,  0.12990319,
       -0.57856073, -0.43655678, -0.66806654, -0.71668198,  0.02389419,
        0.04869878, -0.45436665, -0.22089285, -0.47664217, -0.51504813,
       -0.55818067, -0.60618091, -0.56426029, -0.5063835 ])

In [23]:
final_model = LinearRegression()
final_model.fit(scaled_X_train,y_train)

LinearRegression()

In [27]:
test_pred = final_model.predict(scaled_X_test)
test_pred

array([14.63372092, 19.05502371, 12.60912937, 17.2990722 ,  7.77663186,
        6.82526502, 19.96783499, 17.13494321, 10.38316136, 19.70400344,
        9.4100492 , 13.95881768, 11.61617522, 22.947182  , 18.90183411,
        9.42091718, 12.35426982,  9.41694192,  8.7613977 , 21.27645807,
        6.83781314, 19.30427609, 27.35825582, 24.30865659,  9.45328733,
       11.27279575, 20.73582968,  9.63134669, 12.525551  ,  8.43317338,
        8.79449102, 19.74446296, 10.90697498,  6.92971566, 18.07940374,
        9.45452183, 10.73111886,  9.92794975,  7.07720069, 10.74715111,
       12.15403331, 10.34977084, 11.58588333,  7.61811127, 11.90823723,
       10.76007269,  5.14855579, 15.27095102, 12.95416074, 22.40476607,
       10.72322437, 12.79300442, 14.91953663, 12.22762833, 11.13893795,
        4.91876287, 24.97394881,  9.48559677, 17.27334217, 15.54639358,
       15.02351556, 25.82928505,  8.73778123, 21.26133606, 11.96688674,
       21.76326629])

In [28]:
from sklearn.metrics import mean_absolute_error, mean_squared_error
MAE = mean_absolute_error(y_test, test_pred)
MAE

0.39321852865146933

In [29]:
MSE = mean_squared_error(y_test, test_pred)
MSE

0.31105771364312296

In [30]:
RMSE = np.sqrt(MSE)
RMSE

0.5577254823325926

In [31]:
final_model.coef_

array([  7.15336483,   0.46253336,   0.30906374, -10.29471901,
         4.99345277,  -1.52611765,  -1.29983091,   0.79105902,
         0.25413361,   4.93455393,  -1.4879589 ,   1.36038495,
         0.39332702,  -0.37778386,   0.01927523,   0.73076771,
        -0.29499563,  -0.23108721,  -0.1775098 ])