In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [8]:
df = pd.read_csv(r"D:\Linear Regression\Modular\Linear-Regression\data\Advertising.csv")
df.head()

TV  radio  newspaper  sales
0  230.1   37.8       69.2   22.1
1   44.5   39.3       45.1   10.4
2   17.2   45.9       69.3    9.3
3  151.5   41.3       58.5   18.5
4  180.8   10.8       58.4   12.9

In [9]:
X = df.drop('sales', axis=1)
X.head()

TV  radio  newspaper
0  230.1   37.8       69.2
1   44.5   39.3       45.1
2   17.2   45.9       69.3
3  151.5   41.3       58.5
4  180.8   10.8       58.4

In [10]:
y = df['sales']
y

0      22.1
1      10.4
2       9.3
3      18.5
4      12.9
       ... 
195     7.6
196     9.7
197    12.8
198    25.5
199    13.4
Name: sales, Length: 200, dtype: float64

In [11]:
from sklearn.preprocessing import PolynomialFeatures
from sklearn.linear_model import LinearRegression

In [12]:
poly_conv = PolynomialFeatures(degree=3, include_bias=False)

In [13]:
final_model = LinearRegression()

In [14]:
poly_features = poly_conv.fit_transform(X)

In [15]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(
                                    poly_features, y, test_size=0.33, random_state=101)

In [16]:
from sklearn.preprocessing import StandardScaler

In [17]:
scaler = StandardScaler() #it applies z score normalisation(standardisation)

In [18]:
scaler.fit(X_train)

StandardScaler()

In [19]:
scaled_X_train = scaler.transform(X_train)

In [20]:
scaled_X_test = scaler.transform(X_test)

In [2]:
from sklearn.linear_model import RidgeCV

In [3]:
help(RidgeCV)

Help on class RidgeCV in module sklearn.linear_model._ridge:

class RidgeCV(sklearn.base.MultiOutputMixin, sklearn.base.RegressorMixin, _BaseRidgeCV)
 |  RidgeCV(alphas=(0.1, 1.0, 10.0), *, fit_intercept=True, normalize='deprecated', scoring=None, cv=None, gcv_mode=None, store_cv_values=False, alpha_per_target=False)
 |  
 |  Ridge regression with built-in cross-validation.
 |  
 |  See glossary entry for :term:`cross-validation estimator`.
 |  
 |  By default, it performs efficient Leave-One-Out Cross-Validation.
 |  
 |  Read more in the :ref:`User Guide <ridge_regression>`.
 |  
 |  Parameters
 |  ----------
 |  alphas : ndarray of shape (n_alphas,), default=(0.1, 1.0, 10.0)
 |      Array of alpha values to try.
 |      Regularization strength; must be a positive float. Regularization
 |      improves the conditioning of the problem and reduces the variance of
 |      the estimates. Larger values specify stronger regularization.
 |      Alpha corresponds to ``1 / (2C)`` in other lin

In [5]:
from sklearn.metrics import SCORERS
SCORERS.keys()

dict_keys(['explained_variance', 'r2', 'max_error', 'neg_median_absolute_error', 'neg_mean_absolute_error', 'neg_mean_absolute_percentage_error', 'neg_mean_squared_error', 'neg_mean_squared_log_error', 'neg_root_mean_squared_error', 'neg_mean_poisson_deviance', 'neg_mean_gamma_deviance', 'accuracy', 'top_k_accuracy', 'roc_auc', 'roc_auc_ovr', 'roc_auc_ovo', 'roc_auc_ovr_weighted', 'roc_auc_ovo_weighted', 'balanced_accuracy', 'average_precision', 'neg_log_loss', 'neg_brier_score', 'adjusted_rand_score', 'rand_score', 'homogeneity_score', 'completeness_score', 'v_measure_score', 'mutual_info_score', 'adjusted_mutual_info_score', 'normalized_mutual_info_score', 'fowlkes_mallows_score', 'precision', 'precision_macro', 'precision_micro', 'precision_samples', 'precision_weighted', 'recall', 'recall_macro', 'recall_micro', 'recall_samples', 'recall_weighted', 'f1', 'f1_macro', 'f1_micro', 'f1_samples', 'f1_weighted', 'jaccard', 'jaccard_macro', 'jaccard_micro', 'jaccard_samples', 'jaccard_wei

In [6]:
ridge_cv_model = RidgeCV(alphas=(0.1, 1.0, 10.0), scoring='neg_mean_absolute_error')

In [21]:
ridge_cv_model.fit(scaled_X_train,y_train)

RidgeCV(alphas=array([ 0.1,  1. , 10. ]), scoring='neg_mean_absolute_error')

In [22]:
ridge_cv_model.alpha_ #best alpha hyperparameter

0.1

In [24]:
test_predictions = ridge_cv_model.predict(scaled_X_test)
test_predictions

array([14.29441804, 19.09274078, 12.45657835, 17.11697952,  7.92213878,
        7.11055875, 19.93908808, 17.24961432, 10.28682469, 19.85631473,
        9.37140245, 13.93676075, 11.8445631 , 23.3175409 , 19.29359581,
        9.42610569, 12.44613111,  9.16152967,  8.70067319, 21.41727474,
        7.15087583, 19.37390792, 27.26727867, 24.39398038,  9.19780238,
       11.48707963, 20.44799653,  9.45981126, 12.54834966,  8.39919149,
        8.76754192, 19.91732307, 10.77004173,  7.09693457, 18.17538915,
        9.29856785, 10.54291059,  9.67413599,  7.29781737, 10.72290686,
       12.32886379, 10.33331507, 11.39742423,  7.7308797 , 11.73748995,
       10.61128497,  5.73452753, 15.35361927, 13.03794426, 22.67420852,
       10.59986712, 12.96502029, 14.74166515, 11.9969133 , 11.35618865,
        5.47887637, 24.94004856,  9.41141507, 17.2652532 , 15.60820308,
       15.14933107, 25.70639693,  8.49758236, 21.54616003, 12.12953788,
       21.98002659])

In [25]:
from sklearn.metrics import mean_absolute_error, mean_squared_error

In [26]:
MAE = mean_absolute_error(y_test, test_predictions)
MAE

0.41901199532528305

In [69]:
RMSE = np.sqrt(mean_squared_error(y_test, test_predictions))
RMSE

0.600670302681479

In [27]:
ridge_cv_model.coef_

array([ 5.32298502,  0.6340435 ,  0.45082   , -6.01678743,  4.5650384 ,
       -1.05529106, -1.25112885,  0.47865005, -0.21808315,  2.49274371,
       -1.43382273,  0.77165384,  0.70388686, -0.28850266,  0.18532879,
        0.48908704, -0.1470775 , -0.01268636, -0.03643881])

In [28]:
ridge_cv_model.best_score_ #returns the highest negated mean absolute error

-0.3844802119643976

In [72]:
from sklearn.linear_model import LassoCV

In [73]:
help(LassoCV)

Help on class LassoCV in module sklearn.linear_model._coordinate_descent:

class LassoCV(sklearn.base.RegressorMixin, LinearModelCV)
 |  LassoCV(*, eps=0.001, n_alphas=100, alphas=None, fit_intercept=True, normalize='deprecated', precompute='auto', max_iter=1000, tol=0.0001, copy_X=True, cv=None, verbose=False, n_jobs=None, positive=False, random_state=None, selection='cyclic')
 |  
 |  Lasso linear model with iterative fitting along a regularization path.
 |  
 |  See glossary entry for :term:`cross-validation estimator`.
 |  
 |  The best model is selected by cross-validation.
 |  
 |  The optimization objective for Lasso is::
 |  
 |      (1 / (2 * n_samples)) * ||y - Xw||^2_2 + alpha * ||w||_1
 |  
 |  Read more in the :ref:`User Guide <lasso>`.
 |  
 |  Parameters
 |  ----------
 |  eps : float, default=1e-3
 |      Length of the path. ``eps=1e-3`` means that
 |      ``alpha_min / alpha_max = 1e-3``.
 |  
 |  n_alphas : int, default=100
 |      Number of alphas along the regulariz

In [74]:
lasso_cv_model = LassoCV(eps=0.001, n_alphas=100, cv=10, max_iter=10000000)

In [75]:
lasso_cv_model.fit(scaled_X_train,y_train)

LassoCV(cv=10, max_iter=10000000)

In [76]:
lasso_cv_model.alpha_

0.0048358593581782185

In [77]:
test_predictions = lasso_cv_model.predict(scaled_X_test)

In [78]:
MAE = mean_absolute_error(y_test, test_predictions)
MAE

0.4236488496303237

In [79]:
RMSE = np.sqrt(mean_squared_error(y_test, test_predictions))
RMSE

0.5892189905548018

In [80]:
from sklearn.linear_model import ElasticNetCV

In [81]:
help(ElasticNetCV)

Help on class ElasticNetCV in module sklearn.linear_model._coordinate_descent:

class ElasticNetCV(sklearn.base.RegressorMixin, LinearModelCV)
 |  ElasticNetCV(*, l1_ratio=0.5, eps=0.001, n_alphas=100, alphas=None, fit_intercept=True, normalize='deprecated', precompute='auto', max_iter=1000, tol=0.0001, cv=None, copy_X=True, verbose=0, n_jobs=None, positive=False, random_state=None, selection='cyclic')
 |  
 |  Elastic Net model with iterative fitting along a regularization path.
 |  
 |  See glossary entry for :term:`cross-validation estimator`.
 |  
 |  Read more in the :ref:`User Guide <elastic_net>`.
 |  
 |  Parameters
 |  ----------
 |  l1_ratio : float or list of float, default=0.5
 |      Float between 0 and 1 passed to ElasticNet (scaling between
 |      l1 and l2 penalties). For ``l1_ratio = 0``
 |      the penalty is an L2 penalty. For ``l1_ratio = 1`` it is an L1 penalty.
 |      For ``0 < l1_ratio < 1``, the penalty is a combination of L1 and L2
 |      This parameter can 

In [82]:
elastic_model = ElasticNetCV(l1_ratio=[.1, .5, .7,.9, .95, .99, 1], eps=0.001, n_alphas=100, max_iter=10000000)

In [83]:
elastic_model.fit(scaled_X_train, y_train)

ElasticNetCV(l1_ratio=[0.1, 0.5, 0.7, 0.9, 0.95, 0.99, 1], max_iter=10000000)

In [84]:
elastic_model.l1_ratio_

1.0

In [85]:
test_predictions = elastic_model.predict(scaled_X_test)

In [86]:
MAE = mean_absolute_error(y_test, test_predictions)
MAE

0.4236488496303237

In [87]:
RMSE = np.sqrt(mean_squared_error(y_test, test_predictions))
RMSE

0.5892189905548018

In [88]:
lasso_cv_model.coef_

array([ 4.87579961,  0.11802077,  0.24018055, -5.01491275,  4.36541863,
       -0.22918399, -0.        ,  0.03860951, -0.        ,  1.82671866,
       -0.80741429,  0.        ,  0.13108636, -0.        , -0.        ,
        0.        ,  0.        ,  0.        , -0.        ])